// Editorial School Journal legal pages: plain-language policies with calm reading measure and no decorative friction.
import { Link } from "wouter";
import { ArrowLeft } from "lucide-react";
import { schoolConfig } from "@/lib/school-config";

type LegalKind = "privacy" | "terms";

export default function LegalPage({ kind }: { kind: LegalKind }) {
  const privacy = kind === "privacy";
  return <section className="paper-grain min-h-[70vh] bg-paper py-32 text-ink sm:py-40"><div className="container"><Link href="/" className="focus-ring inline-flex items-center gap-2 text-xs font-extrabold uppercase tracking-[0.13em] text-coral"><ArrowLeft className="h-4 w-4" /> Back to the school</Link><div className="mt-14 max-w-3xl"><p className="chapter-mark">{privacy ? "Policy / 09" : "Policy / 10"}</p><h1 className="mt-7 font-display text-6xl leading-[0.9] tracking-[-0.05em] sm:text-8xl">{privacy ? "Privacy policy" : "Terms of service"}</h1><p className="mt-8 text-sm text-ink-soft">Last updated: 24 August 2026</p><div className="mt-12 space-y-9 border-t border-line pt-10 text-base leading-8 text-ink-soft"><div><h2 className="font-display text-3xl text-ink">A clear promise</h2><p className="mt-3">{privacy ? `${schoolConfig.name} respects the information you choose to share. This site uses submitted contact details only to respond to your enquiry and does not sell or publish personal information.` : `This website is provided by ${schoolConfig.name} as an informational resource for families, learners, staff, and community members. Please use the information thoughtfully and contact the office when a detail needs confirmation.`}</p></div><div><h2 className="font-display text-3xl text-ink">What this site collects</h2><p className="mt-3">{privacy ? "The contact form opens your own email application using a mailto fallback; this site does not store form submissions. Basic anonymous analytics may be used to understand which pages are useful." : "Images, descriptions, dates, and links are shared for school communication. External links and embedded video are governed by their own providers’ terms and privacy policies."}</p></div><div><h2 className="font-display text-3xl text-ink">Questions</h2><p className="mt-3">For questions about this page or how the school handles information, write to <a href={`mailto:${schoolConfig.email}`} className="font-bold text-coral underline decoration-coral/35 underline-offset-4">{schoolConfig.email}</a>.</p></div></div></div></div></section>;
}
